### ISSUE TITLE
Ex11

### ISSUE THREAD

**Issue by arevaloarboled** [RyuseiAndy/cpp_exercises#15]
Hi @RyuseiAndy ,  Exercise specify "implementing the bubble sort only requires moving **iterators forward**". Meaning you cannot decrement an iterator (is not allowed for forward iterators). 
https://github.com/RyuseiAndy/cpp_exercises/blob/b2f486a84628cfc86b3ca2b8f12b061e17015eae/ex11/BubleSort.cpp#L7
If you are using `std::swap`, what is this function doing?
https://github.com/RyuseiAndy/cpp_exercises/blob/b2f486a84628cfc86b3ca2b8f12b061e17015eae/ex11/BubleSort.cpp#L14-L20

**Comment by RyuseiAndy** [comment]
please check file ex11.

**Comment by arevaloarboled** [comment]
Looks good.
