### ISSUE TITLE
Ex13

### ISSUE THREAD

**Issue by arevaloarboled** [RyuseiAndy/cpp_exercises#17]
# Q1
If I use for example "Don't nod?" returns is not palindrome (which is a palindrome). You can improve it by combining remove_if and isalpha.
# Q2
Compute median and the search of k closets points should be done using nth_element as specified in the description of the exercise.

**Comment by RyuseiAndy** [comment]
please check file.

**Comment by arevaloarboled** [comment]
# Q1
Is almost the same, there is nothing to check.
# Q2
Looks good.

**Comment by RyuseiAndy** [comment]
please check file ex13-q1.

**Comment by arevaloarboled** [comment]
Looks good.
